=== Gaoliu19910601/Uintah-1/Packages/Insight/ITK/itk_filter.dtd
<!ELEMENT filter-itk (description, templated, inputs, outputs, parameters, includes)>
  <!ATTLIST filter-itk name CDATA #REQUIRED>

<!ELEMENT description (#PCDATA)>

<!ELEMENT templated (base, template*, defaults*)>

<!ELEMENT base (#PCDATA)>

<!ELEMENT template (#PCDATA)>
  <!ATTLIST template type CDATA #IMPLIED>

<!ELEMENT defaults (default*)>

<!ELEMENT default (#PCDATA)>

<!ELEMENT inputs (input*)>

<!ELEMENT input (value, call, name)>
  <!ATTLIST input num CDATA #REQUIRED>

<!ELEMENT value (#PCDATA)>

<!ELEMENT call (#PCDATA)>
  <!ATTLIST call const (yes|no) "no">

<!ELEMENT name (#PCDATA)>

<!ELEMENT outputs (output*)>

<!ELEMENT output (value, call, name)>
  <!ATTLIST output num CDATA #REQUIRED>

<!ELEMENT parameters (param*)>

<!ELEMENT param (name, type, call)>

<!ELEMENT type (#PCDATA)>

<!ELEMENT includes (file*)>

<!ELEMENT file (#PCDATA)>

=== Gaoliu19910601/Uintah-1/Packages/Insight/ITK/itk_GradientMagnitudeImageFilter.xml
<?xml version="1.0"?>
<!DOCTYPE filter-itk SYSTEM "itk_filter.dtd">
<filter-itk name="itk::GradientMagnitudeImageFilter">
  <description>
Computes the gradient magnitude of an image region at each pixel.
  </description>
  <templated>
    <base>itk::Object</base>
    <template>InputImageType</template>
    <template>OutputImageType</template>
    <defaults>
      <default>itk::Image&lt;unsigned char, 2&gt;</default>
      <default>itk::Image&lt;float, 2&gt;</default>
    </defaults>
  </templated>

  <inputs>
    <input num="1">
      <value>InputImageType</value>
      <call>SetInput</call>
      <name>InputImage</name>
    </input>  
  </inputs>
  <outputs>
    <output num="1">
      <value>OutputImageType</value>
      <call>GetOutput</call>
      <name>OutputImage</name>
    </output>
  </outputs>

  <parameters>
  </parameters>

  <includes>
    <file>itkGradientMagnitudeImageFilter.h</file>
  </includes>
</filter-itk>

=== Gaoliu19910601/Uintah-1/Packages/Insight/ITK/itk_MeanImageFilter.xml
<?xml version="1.0"?>
<!DOCTYPE filter-itk SYSTEM "itk_filter.dtd">
<filter-itk name="itk::MeanImageFilter">
  <description>
Applies an averaging filter to an image.  Computes an image where a given pixel is the mean value of the the pixels in a neighborhood about the corresponding input pixel. 
  </description>
  <templated>
    <template>InputImageType</template>
    <template>OutputImageType</template>
    <defaults>
      <default>itk::Image&lt;float, 2&gt;</default>
      <default>itk::Image&lt;float, 2&gt;</default>
    </defaults>
    <defaults>
      <default>itk::Image&lt;float, 3&gt;</default>
      <default>itk::Image&lt;float, 3&gt;</default>
    </defaults>
  </templated>

  <datatypes>
    <datatype name="FilterType::InputSizeType">
      <field>
        <access-method>array</access-method>
        <type>double</type>
        <variable-call>GetSizeDimension</variable-call>
      </field>
    </datatype>
  </datatypes>

  <inputs>
    <input name="InputImage">
      <type>InputImageType</type>
      <call>SetInput</call>
    </input>  
  </inputs>
  <outputs>
    <output name="OutputImage">
      <type>OutputImageType</type>
      <call>GetOutput</call>
    </output>
  </outputs>

  <parameters>
    <param defined="yes">
      <name>radius</name>
      <type>FilterType::InputSizeType</type>
      <call>SetRadius</call>
    </param>
  </parameters>

  <includes>
    <file>itkMeanImageFilter.h</file>
  </includes>
</filter-itk>
