=== Gaoliu19910601/Uintah-1/Packages/Insight/Dataflow/Modules/Filters/XML/gui_filter.dtd
<!--
  The contents of this file are subject to the University of Utah Public
  License (the "License"); you may not use this file except in compliance
  with the License.
  
  Software distributed under the License is distributed on an "AS IS"
  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
  License for the specific language governing rights and limitations under
  the License.
  
  The Original Source Code is SCIRun, released March 12, 2001.
  
  The Original Source Code was developed by the University of Utah.
  Portions created by UNIVERSITY are Copyright (C) 2001, 1994 
  University of Utah. All Rights Reserved.
-->

<!ELEMENT filter-gui (parameters*)>
  <!ATTLIST filter-gui name CDATA #REQUIRED>

<!ELEMENT parameters (param*)>

<!ELEMENT param (gui, min?, max?, values?, default)>
  <!ATTLIST param name CDATA #REQUIRED>

<!ELEMENT gui (#PCDATA)>

<!ELEMENT min (#PCDATA)>

<!ELEMENT max (#PCDATA)>

<!ELEMENT values (val+)>

<!ELEMENT val (#PCDATA)>

<!ELEMENT default (#PCDATA)>

=== Gaoliu19910601/Uintah-1/Packages/Insight/Dataflow/Modules/Filters/XML/gui_WatershedSegmentTreeGenerator_Darby.xml
<?xml version="1.0"  encoding="iso-8859-1"?>
<!DOCTYPE filter-gui SYSTEM "gui_filter.dtd">
<filter-gui name="WatershedSegmenterTreeGeneratorGui_Darby">
  <parameters>
    <param name="flood_level">
      <gui>text-entry</gui>
      <default>0.25</default>
    </param>
    <param name="merge">
      <gui>text-entry</gui>
      <default>0</default>
    </param>
  </parameters>

</filter-gui>

=== Gaoliu19910601/Uintah-1/Packages/Insight/Dataflow/Modules/Filters/XML/gui_ReflectImageFilter.xml
<?xml version="1.0"  encoding="iso-8859-1"?>
<!DOCTYPE filter-gui SYSTEM "gui_filter.dtd">
<filter-gui name="GradientAnistotropicDiffusionImageFilter">
  <parameters>
    <param name="direction">
      <gui>radiobutton</gui>
      <values>
      <val>0</val>
      <val>1</val>
      </values>
      <default>1</default>
    </param>
  </parameters>

</filter-gui>
