=== Gaoliu19910601/Uintah-1/Packages/Insight/Dataflow/Modules/Filters/XML/sci_filter.dtd
<!ELEMENT filter (include+, filter-sci)>
  <!ATTLIST filter name  CDATA #REQUIRED>

<!ELEMENT include EMPTY>
  <!ATTLIST include href CDATA #REQUIRED>

<!ELEMENT filter-sci (package, category, instantiations, includes)>
  <!ATTLIST filter-sci name CDATA #REQUIRED>

<!ELEMENT package (#PCDATA)>

<!ELEMENT category (#PCDATA)>

<!ELEMENT instantiations (instance*)>
  <!ATTLIST instantiations use-defaults (yes|no) "no">

<!ELEMENT instance (type+)>
  <!ATTLIST instance num CDATA #REQUIRED>

<!ELEMENT type (value)>
  <!ATTLIST type name CDATA #REQUIRED>

<!ELEMENT value (#PCDATA)>

<!ELEMENT includes (file*)>

<!ELEMENT file (#PCDATA)>

=== Gaoliu19910601/Uintah-1/Packages/Insight/Dataflow/Modules/Filters/XML/sci_ThresholdSegmentationLevelSetImageFilter.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE filter SYSTEM "sci_filter.dtd">
<filter name="ThresholdSegmentationLevelSetImageFilter">
  <include href="ITK/itk_ThresholdSegmentationLevelSetImageFilter.xml"/>
  <include href="Dataflow/Modules/Filters/XML/gui_ThresholdSegmentationLevelSetImageFilter_Darby.xml"/>

<filter-sci name="ThresholdSegmentationLevelSetImageFilter">
  <package>Insight</package>

  <category>Filters</category>

  <instantiations>
    <instance num="1">
      <type name="ImageType">
        <value>itk::Image&lt;float, 2&gt;</value>
      </type>
      <type name="FeatureImageType">
        <value>itk::Image&lt;float, 2&gt;</value>
      </type>
     </instance>
  </instantiations>

  <includes>
    <file>Packages/Insight/Dataflow/Ports/ITKDatatypePort.h</file>
  </includes>

</filter-sci>

</filter>

=== Gaoliu19910601/Uintah-1/Packages/Insight/Dataflow/Modules/Filters/XML/sci_BinaryThresholdImageFilter.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE filter SYSTEM "sci_filter.dtd">
<filter name="BinaryThresholdImageFilter">
   <include href="ITK/itk_BinaryThresholdImageFilter.xml"/>
   <include href="Dataflow/Modules/Filters/XML/gui_BinaryThresholdImageFilter.xml"/>
   <filter-sci name="BinaryThresholdImageFilter">
      <package>Insight</package>
      <category>Filters</category>
      <instantiations use-defaults="yes"/>
     <includes>
        <file>Packages/Insight/Dataflow/Ports/ITKDatatypePort.h</file>
     </includes>
  </filter-sci>
</filter>

=== Gaoliu19910601/Uintah-1/Packages/Insight/Dataflow/Modules/Filters/XML/sci_GradientMagnitudeImageFilter.xml
<?xml version="1.0"?>
<!DOCTYPE filter SYSTEM "sci_filter.dtd">
<filter name="GradientMagnitude">
  <include href="ITK/itk_GradientMagnitudeImageFilter.xml"/>
  <include href="Dataflow/Modules/Filters/XML/gui_GradientMagnitudeImageFilter_Darby.xml"/>

<filter-sci name="GradientMagnitude">
  <package>Insight</package>

  <category>Filters</category>

  <instantiations>
    <instance num="1">
      <type name="InputImageType">
        <value>itk::Image&lt;float, 2&gt;</value>
      </type>
      <type name="OutputImageType">
        <value>itk::Image&lt;float, 2&gt;</value>
      </type>
     </instance>
    <instance num="2">
      <type name="InputImageType">
        <value>itk::Image&lt;float, 3&gt;</value>
      </type>
      <type name="OutputImageType">
        <value>itk::Image&lt;float, 3&gt;</value>
      </type>
     </instance>
  </instantiations>

  <includes>
    <file>Packages/Insight/Dataflow/Ports/ITKDatatypePort.h</file>
  </includes>

</filter-sci>

</filter>
