=== Gaoliu19910601/Uintah-1/Dataflow/Modules/Fields/Manip/srcs.dtd
<!-- Top level -->
<!ELEMENT srcs (src+)>

<!ELEMENT src (description, lib*, libpath*, inc*)>
<!ATTLIST src name CDATA #REQUIRED>

<!-- Describe the manipulation -->
<!ELEMENT description (#PCDATA)>

<!-- gets turned into -lmyneededlib on the compile line -->
<!ELEMENT lib EMPTY>
<!ATTLIST lib name CDATA #REQUIRED>

<!-- gets turned into -L/my/needed/lib/path on the compile line -->
<!ELEMENT libpath EMPTY>
<!ATTLIST libpath name CDATA #REQUIRED>

<!-- gets turned into -I/my/needed/include/path on the compile line -->
<!ELEMENT inc EMPTY>
<!ATTLIST inc name CDATA #REQUIRED>

=== Gaoliu19910601/Uintah-1/src/Dataflow/Modules/Fields/Manip/srcs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE srcs SYSTEM "srcs.dtd">

<srcs>
  <src name="test">
    <description>Nifty new test for dynamic compilation and loading</description>
    <lib name="Core_Datatypes"/>
    <libpath name="../../../../lib"/>
    <inc name="/usr/local/bogusdir/include"/>
  </src>
   <src name="boo">
    <description>Nifty new test for dynamic compilation and loading</description>
    <lib name="Core_Datatypes"/>
    <libpath name="../../../../lib"/>
    <inc name="/usr/local/boodir/include"/>
  </src> 
</srcs>
